adventureworks:
  target: postgres
  outputs:
    duckdb:
     type: duckdb
     path: target/adventureworks.duckdb
     threads: 12
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: adventureworks
      schema: dbo
      threads: 12
    bigquery:  
      dataset: adventureworks
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/kojiroyamamoto/Projects/blog/lightdash/lightdash-credential.json
      location: US
      method: service-account
      priority: interactive
      project: lightdash-408501
      threads: 1
      type: bigquery
